-- Insert Scripture Books
INSERT INTO scripture_books (id, name, code) VALUES
(1, 'Antiguo Testamento', 'OLD_TESTAMENT'),
(2, 'Nuevo Testamento', 'NEW_TESTAMENT'),
(3, 'Libro de Mormón', 'BOOK_OF_MORMON'),
(4, 'Doctrina y Convenios e Historia de la Iglesia', 'DOCTRINE_COVENANTS');

-- Insert Verses - Antiguo Testamento
INSERT INTO verses (text, reference, book_id) VALUES
('… esta es mi obra y mi gloria: Llevar a cabo la inmortalidad y la vida eterna del hombre', 'Moisés 1:39', 1),
('Y el Señor llamó Sion a su pueblo, porque eran uno en corazón y voluntad', 'Moisés 7:18', 1),
('El Señor prometió a Abraham que su descendencia llevaría ''este ministerio y sacerdocio a todas las naciones''', 'Abraham 2:9–11', 1),
('Como espíritus, fuimos ''organizad[o]s antes que existiera el mundo''', 'Abraham 3:22–23', 1),
('… creó Dios al hombre a su imagen', 'Génesis 1:26–27', 1),
('… el hombre […] se allegará a su mujer, y serán una sola carne', 'Génesis 2:24', 1),
('… ¿cómo, pues, haría yo este gran mal y pecaría contra Dios?', 'Génesis 39:9', 1),
('Los Diez Mandamientos', 'Éxodo 20:3–17', 1),
('… escogeos hoy a quién sirváis', 'Josué 24:15', 1),
('¿Y quién estará en su lugar santo? El limpio de manos y puro de corazón', 'Salmos 24:3–4', 1),
('Confía en Jehová con todo tu corazón […] y él enderezará tus veredas', 'Proverbios 3:5–6', 1),
('… aunque vuestros pecados sean como la grana, como la nieve serán emblanquecidos', 'Isaías 1:18', 1),
('Ay de los que a lo malo llaman bueno, y a lo bueno, malo', 'Isaías 5:20', 1),
('La restauración del Evangelio es ''una obra maravillosa y un prodigio''', 'Isaías 29:13–14', 1),
('Ciertamente llevó [Jesucristo] nuestras enfermedades y sufrió nuestros dolores', 'Isaías 53:3–5', 1),
('Las bendiciones del ayuno apropiado', 'Isaías 58:6–7', 1),
('[Retráete] […] de hacer tu voluntad en mi día santo, y [llámalo] delicia', 'Isaías 58:13–14', 1),
('Antes que te formase en el vientre […] te di por profeta a las naciones', 'Jeremías 1:4–5', 1),
('El profeta es ''atalaya a la casa de Israel''', 'Ezequiel 3:16–17', 1),
('La Biblia y el Libro de Mormón ''serán uno solo en tu mano''', 'Ezequiel 37:15–17', 1),
('Dios ''levantará un reino que no será jamás destruido''', 'Daniel 2:44–45', 1),
('… Jehová el Señor […] revel[a] su secreto a sus siervos los profetas', 'Amós 3:7', 1),
('Las bendiciones de pagar el diezmo', 'Malaquías 3:8–10', 1),
('Elías ''hará volver […] el corazón de los hijos hacia los padres''', 'Malaquías 4:5–6', 1);

-- Insert Verses - Nuevo Testamento
INSERT INTO verses (text, reference, book_id) VALUES
('Así alumbre vuestra luz delante de los hombres', 'Mateo 5:14–16', 2),
('Venid a mí todos los que estáis trabajados y cargados, y yo os haré descansar', 'Mateo 11:28–30', 2),
('Jesús dijo: ''… a ti te daré las llaves del reino de los cielos''', 'Mateo 16:15–19', 2),
('Amarás al Señor tu Dios […]. Amarás a tu prójimo', 'Mateo 22:36–39', 2),
('[Q]ue os ha nacido hoy, en la ciudad de David, un Salvador, que es CRISTO el Señor', 'Lucas 2:10–12', 2),
('Jesucristo mandó que participáramos de la Santa Cena ''en memoria de [Él]''', 'Lucas 22:19–20', 2),
('… porque un espíritu no tiene carne ni huesos como veis que yo tengo', 'Lucas 24:36–39', 2),
('… el que no naciere de agua y del Espíritu no puede entrar en el reino de Dios', 'Juan 3:5', 2),
('Porque de tal manera amó Dios al mundo que ha dado a su Hijo Unigénito', 'Juan 3:16', 2),
('El que quiera hacer la voluntad de él conocerá si la doctrina es de Dios', 'Juan 7:17', 2),
('Y esta es la vida eterna: que te conozcan a ti, el único Dios verdadero, y a Jesucristo', 'Juan 17:3', 2),
('… vuestro cuerpo es templo del Espíritu Santo', '1 Corintios 6:19–20', 2),
('Pero en el Señor, ni el varón es sin la mujer, ni la mujer sin el varón', '1 Corintios 11:11', 2),
('… así como en Adán todos mueren, así también en Cristo todos serán vivificados', '1 Corintios 15:20–22', 2),
('En la resurrección hay tres grados de gloria', '1 Corintios 15:40–42', 2),
('Dios reunirá ''todas las cosas en Cristo, en la dispensación del cumplimiento de los tiempos''', 'Efesios 1:10', 2),
('La Iglesia está edificada ''sobre el fundamento de los apóstoles y profetas, siendo la principal piedra del ángulo Jesucristo mismo''', 'Efesios 2:19–20', 2),
('… el día del Señor […] no vendrá sin que antes venga la apostasía', '2 Tesalonicenses 2:1–3', 2),
('… las Sagradas Escrituras […] te pueden hacer sabio para la salvación', '2 Timoteo 3:15–17', 2),
('El Padre Celestial es el ''Padre de los espíritus''', 'Hebreos 12:9', 2),
('Y si alguno de vosotros tiene falta de sabiduría, pídala a Dios', 'Santiago 1:5–6', 2),
('… la fe, si no tiene obras, es muerta', 'Santiago 2:17–18', 2),
('… también ha sido predicado el evangelio a los muertos', '1 Pedro 4:6', 2),
('… Y fueron juzgados los muertos […] según sus obras', 'Apocalipsis 20:12', 2);

-- Insert Verses - Libro de Mormón
INSERT INTO verses (text, reference, book_id) VALUES
('Iré y haré lo que el Señor ha mandado', '1 Nefi 3:7', 3),
('Adán cayó para que los hombres existiesen; y existen los hombres para que tengan gozo', '2 Nefi 2:25', 3),
('son libres para escoger la libertad y la vida eterna, o la cautividad y la muerte', '2 Nefi 2:27', 3),
('todos son iguales ante Dios', '2 Nefi 26:33', 3),
('Dios dará a los hijos de los hombres línea por línea, precepto por precepto', '2 Nefi 28:30', 3),
('Deleitaos en las palabras de Cristo; porque he aquí, las palabras de Cristo os dirán todas las cosas que debéis hacer', '2 Nefi 32:3', 3),
('debéis orar siempre', '2 Nefi 32:8–9', 3),
('cuando os halláis al servicio de vuestros semejantes, solo estáis al servicio de vuestro Dios', 'Mosíah 2:17', 3),
('aquellos que guardan los mandamientos de Dios son bendecidos en todas las cosas', 'Mosíah 2:41', 3),
('despoj[aos] del hombre natural, y [haceos] santo[s] por la expiación de Cristo el Señor', 'Mosíah 3:19', 3),
('Creed en Dios; creed que él tiene toda sabiduría', 'Mosíah 4:9', 3),
('bautiza[os] en el nombre del Señor, como testimonio de que habéis concertado un convenio con él', 'Mosíah 18:8–10', 3),
('Y él saldrá, sufriendo dolores, aflicciones y tentaciones de todas clases', 'Alma 7:11–13', 3),
('es necesario que se realice una expiación, un sacrificio infinito y eterno', 'Alma 34:9–10', 3),
('no te dej[es] llevar más por las concupiscencias de tus ojos', 'Alma 39:9', 3),
('la maldad nunca fue felicidad', 'Alma 41:10', 3),
('es sobre la roca de nuestro Redentor donde debéis establecer vuestro fundamento', 'Helamán 5:12', 3),
('me he sometido a la voluntad del Padre en todas las cosas desde el principio', '3 Nefi 11:10–11', 3),
('[sed] perfectos así como yo, o como vuestro Padre que está en los cielos es perfecto', '3 Nefi 12:48', 3),
('venid a mí y sed bautizados, para que seáis santificados por la recepción del Espíritu Santo', '3 Nefi 27:20', 3),
('no recibís ningún testimonio sino hasta después de la prueba de vuestra fe', 'Éter 12:6', 3),
('si los hombres vienen a mí, entonces haré que las cosas débiles sean fuertes para ellos', 'Éter 12:27', 3),
('la caridad es el amor puro de Cristo', 'Moroni 7:45–48', 3),
('[pedid] con un corazón sincero, con verdadera intención, teniendo fe en Cristo; y por el poder del Espíritu Santo podréis conocer la verdad de todas las cosas', 'Moroni 10:4–5', 3);

-- Insert Verses - Doctrina y Convenios
INSERT INTO verses (text, reference, book_id) VALUES
('José Smith vio a dos Personajes, cuyo fulgor y gloria no admiten descripción', 'José Smith—Historia 1:15–20', 4),
('la única iglesia verdadera y viviente', 'Doctrina y Convenios 1:30', 4),
('sea por mi propia voz o por la voz de mis siervos, es lo mismo', 'Doctrina y Convenios 1:37–38', 4),
('Mirad hacia mí en todo pensamiento; no dudéis; no temáis', 'Doctrina y Convenios 6:36', 4),
('hablaré a tu mente y a tu corazón por medio del Espíritu Santo', 'Doctrina y Convenios 8:2–3', 4),
('El Sacerdocio Aarónico tiene las llaves del ministerio de ángeles, y del evangelio de arrepentimiento, y del bautismo', 'Doctrina y Convenios 13:1', 4),
('el valor de las almas es grande a la vista de Dios', 'Doctrina y Convenios 18:10–11', 4),
('¡cuán grande no será vuestro gozo si me trajereis muchas almas!', 'Doctrina y Convenios 18:15–16', 4),
('yo, Jesucristo, he padecido estas cosas por todos', 'Doctrina y Convenios 19:16–19', 4),
('recibiréis la palabra del profeta como si viniera de mi propia boca', 'Doctrina y Convenios 21:4–6', 4),
('con poder y gran gloria me revelaré desde los cielos y moraré en rectitud con los hombres sobre la tierra mil años', 'Doctrina y Convenios 29:10–11', 4),
('el matrimonio lo decretó Dios', 'Doctrina y Convenios 49:15–17', 4),
('quien se ha arrepentido de sus pecados es perdonado', 'Doctrina y Convenios 58:42–43', 4),
('a vosotros os es requerido perdonar a todos los hombres', 'Doctrina y Convenios 64:9–11', 4),
('por Jesucristo los mundos son y fueron creados', 'Doctrina y Convenios 76:22–24', 4),
('Yo, el Señor, estoy obligado cuando hacéis lo que os digo', 'Doctrina y Convenios 82:10', 4),
('en sus ordenanzas se manifiesta el poder de la divinidad', 'Doctrina y Convenios 84:20–22', 4),
('buscad conocimiento, tanto por el estudio como por la fe', 'Doctrina y Convenios 88:118', 4),
('Las bendiciones de vivir la Palabra de Sabiduría', 'Doctrina y Convenios 89:18–21', 4),
('El Sacerdocio de Melquisedec tiene poder y autoridad para administrar en las cosas espirituales', 'Doctrina y Convenios 107:8', 4),
('los derechos del sacerdocio no pueden ser gobernados ni manejados sino conforme a los principios de la rectitud', 'Doctrina y Convenios 121:36, 41–42', 4),
('Dios ha revelado su poder, su gloria y su amor en todas las cosas', 'Doctrina y Convenios 130:18–19', 4),
('si somos fieles, seremos exaltados', 'Doctrina y Convenios 132:19', 4);